### ISSUE TITLE
Lab4 - Contoso.Events.DataGeneration debugging error - "system.formatexception"

### ISSUE THREAD

**Issue by willam-gregoire** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#16]
Error when debugging Contoso.Events.DataGeneration.

What can I do?

System.FormatException was unhandled
  HResult=-2146233033
  Message=String was not recognized as a valid DateTime.
  Source=mscorlib
  StackTrace:
       at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
       at System.DateTime.Parse(String s)
       at Contoso.Events.DataGeneration.Program.Main(String[] args) in C:\labs\20532-DevelopingMicrosoftAzureSolutions-master\Allfiles\Mod04\Labfiles\Starter\Contoso.Events\Contoso.Events.DataGeneration\Program.cs:line 21
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

These is a sample of the data to be inserted:

...
context.Events.AddRange(
                    new List<Event>
                    {
                        new Event
                        {
                          EventKey = "FY17SepGeneralConference",
                          StartTime = DateTime.Parse("9/7/2017 3:40:00 PM"),
                          EndTime = DateTime.Parse("9/11/2017 3:40:00 AM"),
                          Title = "FY17 September Technical Conference",
                          Description = "Sed in euismod mi, sed pellentesque tortor. Aenean ac massa dolor. Fusce in ligula a nisl lacinia fermentum a ac mi. Vivamus placerat at nunc ut egestas. Suspendisse eu diam interdum, laoreet turpis at, volutpat sem. Maecenas adipiscing fringilla orci, eget venenatis turpis pharetra a. Sed cursus neque arcu, sed malesuada nisl blandit ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean ac fringilla nisl. Aenean blandit tempus dignissim. Pellentesque vehicula dapibus nibh, in rutrum mi dignissim quis. Nulla condimentum ipsum vitae metus interdum, scelerisque rutrum lorem hendrerit. Phasellus tempor venenatis dolor, ac interdum mi aliquam nec. Fusce vitae felis vel odio elementum facilisis nec sed magna. Aenean scelerisque sed neque quis sodales.",
                          RegistrationCount = 21
                        },

**Comment by seesharprun** [comment]
I'm having a hard time reproducing this issue.  Is it a localization issue?  If you don't mind me asking, what language are you using for the virtual machine?

My next idea is to hard-code the dates into a language-agnostic format (ISO maybe) to see if that works.

**Comment by seesharprun** [comment]
I believe this is a localization issue.  I would have to update the dates in each DataGeneration project to use the ISO 8601 format.  So for example:

    StartTime = DateTime.Parse("9/7/2017 3:40:00 PM"),

would now be

    StartTime = DateTime.ParseExact("2017-09-07T15:40:00.0000000", "o", null),

That makes the dates language-agnostic.

**Comment by willam-gregoire** [comment]
Thanks for looking into this Sidney. I'm indeed using Spanish locals... What do you recomend?
